export interface L2Item {
  label: string;
}
export interface L1Item {
  label: string;
  l2: L2Item[];
}
export interface NavSection {
  id: string;
  label: string;
  goTo: string;
  l1: L1Item[];
}

export const NAV_DATA: NavSection[] = [
  {
    id: "utbildning",
    label: "Utbildning",
    goTo: "Gå till Utbildning",
    l1: [
      { label: "Program och kurser", l2: [
        { label: "Högskoleingenjörs- och kandidatprogram" },
        { label: "Civilingenjörsprogram" },
        { label: "Arkitektprogram" },
        { label: "Sjöbefälsprogram" },
        { label: "Masterprogram" },
        { label: "Förberedande utbildning" },
        { label: "Ämneslärarutbildning" },
        { label: "Fristående kurser" },
        { label: "Vidareutbildning och kompetensutveckling" },
        { label: "Program under avveckling" },
      ]},
      { label: "Anmälan och behörighet", l2: [
        { label: "Från anmälan till antagning" },
        { label: "Efter antagningsbeskedet" },
        { label: "Statistik och antagningspoäng" },
        { label: "Masterprogram för Chalmersstudenter" },
        { label: "Studieavgifter" },
        { label: "Stipendier för avgiftsbetalande masterstudenter" },
        { label: "Datum och deadlines för masterstudier" },
      ]},
      { label: "Studera hos oss", l2: [
        { label: "Studentliv" },
        { label: "Studentstaden Göteborg" },
        { label: "Så funkar studierna" },
        { label: "Möt oss" },
        { label: "Lär känna några av våra tidigare studenter" },
        { label: "Utbytesstudier" },
      ]},
      { label: "Ny student", l2: [
        { label: "Det här behöver du göra som ny student" },
        { label: "Mottagning för nya grundstudenter" },
        { label: "Mottagning för Tekniskt basår" },
      ]},
      { label: "Studentstöd", l2: [
        { label: "Studievägledning och stöd" },
        { label: "Riktat pedagogiskt stöd för dig med funktionsnedsättning" },
        { label: "Studenthälsa" },
        { label: "Resurser för språk och skrivande" },
        { label: "Mattestöd" },
        { label: "It-support" },
      ]},
      { label: "Examen och karriär", l2: [
        { label: "Ta ut din examen" },
        { label: "Examina på Chalmers" },
        { label: "Examensbevis och Diploma Supplement" },
        { label: "Verifiera utbildning och examen" },
        { label: "Examensceremoni" },
        { label: "Chalmers karriärvägledning" },
        { label: "Entreprenörscoachning" },
        { label: "Att vara Chalmersalumn" },
      ]},
      { label: "Dina studier", l2: [
        { label: "Planera och genomföra studier" },
        { label: "Hitta kurs- och programplaner" },
        { label: "Kursval och registrering" },
        { label: "Kandidat- och examensarbete" },
        { label: "Rättigheter och skyldigheter" },
        { label: "Studie- och arbetsmiljö" },
        { label: "Tentamen och övrig examination" },
        { label: "Tjänster och verktyg" },
        { label: "Utbytesstudier och internationella möjligheter" },
      ]},
    ],
  },
  {
    id: "forskning",
    label: "Forskning",
    goTo: "Gå till Forskning",
    l1: [
      { label: "Centrum",                   l2: [] },
      { label: "Forskningsområden i urval", l2: [
        { label: "Energi" },
        { label: "Hälsa och teknik" },
        { label: "IKT" },
        { label: "Materialvetenskap" },
        { label: "Nano" },
        { label: "Produktion" },
        { label: "Transport" },
        { label: "Ocean" },
        { label: "Rymd" },
        { label: "Mark" },
        { label: "Batterier" },
      ]},
      { label: "Vi utbildar nya forskare", l2: [
        { label: "Om forskarutbildningen" },
        { label: "Doktorandkurser" },
        { label: "Doktorandkurser i samverkan" },
        { label: "Forskarskolor" },
      ]},
      { label: "Möt våra forskare", l2: [
        { label: "Chalmersforskare i Kungl. vetenskapsakademin" },
        { label: "Chalmersforskare i Sveriges unga akademi" },
        { label: "Forskare med ERC-anslag" },
        { label: "Jubileumsprofessorer" },
        { label: "Wallenberg Scholars" },
        { label: "Forskarporträtt" },
      ]},
      { label: "Forskningsinfrastrukturer", l2: [] },
      { label: "Populärvetenskap", l2: [
        { label: "Vetenskapsfestivalen" },
        { label: "Chalmers i Almedalen 2025" },
      ]},
    ],
  },
  {
    id: "samarbete",
    label: "Samarbete",
    goTo: "Samarbeta med oss",
    l1: [
      { label: "Samarbeta inom forskning", l2: [
        { label: "Forskningsnära kontakter" },
        { label: "Idrottsteknologi" },
        { label: "Forskningsnära utveckling" },
      ]},
      { label: "Samarbete i utbildning och med studenter", l2: [
        { label: "Erbjud examensarbete och jobb" },
      ]},
      { label: "Partnerskap och nätverk", l2: [
        { label: "Strategiska partnerskap" },
        { label: "Akademiska allianser och nätverk" },
        { label: "Utbytesinformation för partneruniversitet" },
        { label: "Chalmers roll i totalförsvaret" },
        { label: "Chalmers engagemang i MAX IV och ESS" },
        { label: "Batterisatsningen Compel" },
      ]},
      { label: "Aktiviteter för skolan", l2: [
        { label: "Upplev fysik hos Fysiklek" },
        { label: "Rädda Ägget åk 5" },
        { label: "Tekniktävlingen åk 6" },
        { label: "Teknikåttan" },
        { label: "Girls Code Club" },
        { label: "Utställningen Unga forskare" },
        { label: "Rymden – aktiviteter för skolan" },
        { label: "Matematik – aktiviteter för skolan" },
        { label: "Kemi – aktiviteter för skolan" },
        { label: "Creative Code" },
        { label: "FIRST LEGO League" },
      ]},
      { label: "Stöd Chalmers", l2: [
        { label: "Rikta din gåva dit du vill" },
        { label: "Så här donerar du" },
        { label: "Chalmers donatorer" },
        { label: "I William Chalmers fotspår" },
        { label: "Kontakta Chalmers advancement office" },
      ]},
      { label: "Entreprenörskap och innovation", l2: [
        { label: "Entrepreneurial Minds" },
        { label: "Infrastruktur för innovationsstöd" },
        { label: "Chalmers Entrepreneurial Fellowship" },
      ]},
    ],
  },
  {
    id: "om-oss",
    label: "Om oss",
    goTo: "Om Chalmers",
    l1: [
      { label: "Arbeta hos oss", l2: [
        { label: "Chalmers som arbetsgivare" },
        { label: "För dig som söker jobb hos oss" },
        { label: "Lediga tjänster" },
        { label: "Anställningsordningar och akademiska karriärvägar vid Chalmers" },
        { label: "Göteborg" },
        { label: "Jobbuppdrag för Chalmers studenter" },
        { label: "Biträdande universitetslektor" },
      ]},
      { label: "Organisation och styrning", l2: [
        { label: "Vision och strategi" },
        { label: "Jämlikhet på Chalmers" },
        { label: "Organisation" },
        { label: "Så styrs Chalmers" },
        { label: "Stiftelsen Chalmers tekniska högskola" },
        { label: "Kvalitetsarbete" },
      ]},
      { label: "Chalmers i siffror",         l2: [] },
      { label: "Campus och lokaler", l2: [
        { label: "Besök Chalmers" },
        { label: "Projekt Ett samlat campus på Johanneberg" },
      ]},
      { label: "Tradition och högtider",     l2: [] },
      { label: "Alumn", l2: [
        { label: "Alumnerbjudande" },
        { label: "Kommande evenemang" },
        { label: "Håll kontakten" },
        { label: "Engagera dig" },
        { label: "Kompetensutveckling" },
        { label: "Årets alumn" },
        { label: "CING och andra föreningar" },
        { label: "Kontakta Chalmers Alumnkontor" },
        { label: "Alumndagen 2025" },
        { label: "Wall of fame" },
      ]},
      { label: "Kontakt", l2: [
        { label: "Chalmers Servicecenter" },
        { label: "För leverantörer" },
        { label: "Visselblåsning vid misstanke om missförhållande" },
        { label: "Hittegods" },
      ]},
      { label: "Om webbplatsen", l2: [
        { label: "Kakor Cookies" },
        { label: "Hantering av personuppgifter" },
        { label: "Tillgänglighetsredogörelse" },
      ]},
    ],
  },
  {
    id: "aktuellt",
    label: "Aktuellt",
    goTo: "Gå till Aktuellt",
    l1: [
      { label: "Nyheter",             l2: [] },
      { label: "Kalender",            l2: [] },
      { label: "Konferens",           l2: [] },
      { label: "Press och media",     l2: [] },
      { label: "Följ oss",            l2: [] },
      { label: "Rektor kommenterar",  l2: [] },
      { label: "Ämnen i fokus",       l2: [] },
    ],
  },
  {
    id: "institutioner",
    label: "Institutioner",
    goTo: "Gå till Institutioner",
    l1: [
      { label: "Arkitektur och samhällsbyggnadsteknik", l2: [
        { label: "Utbildning" },
        { label: "Forskning" },
        { label: "Centrum och infrastrukturer" },
        { label: "Resurser och samarbeten" },
        { label: "Organisation" },
        { label: "Kontakt" },
      ]},
      { label: "Data och informationsteknik", l2: [
        { label: "Forskning" },
        { label: "Utbildning" },
        { label: "Centrum och samarbeten" },
        { label: "Kontakt" },
        { label: "Arbeta på CSE" },
      ]},
      { label: "Elektroteknik", l2: [
        { label: "Forskning" },
        { label: "Utbildning" },
        { label: "Resurser och samarbeten" },
        { label: "Kontakt" },
      ]},
      { label: "Fysik och astronomi", l2: [
        { label: "Forskning" },
        { label: "Utbildning" },
        { label: "Infrastrukturer och centrum" },
        { label: "Samhälle och näringsliv" },
        { label: "Om oss" },
        { label: "Kontakt" },
      ]},
      { label: "Kemi och kemiteknik", l2: [
        { label: "Forskning" },
        { label: "Utbildning" },
        { label: "Resurser och samarbeten" },
        { label: "Kontakt" },
      ]},
      { label: "Life sciences", l2: [
        { label: "Forskning" },
        { label: "Utbildning" },
        { label: "Resurser och samarbeten" },
        { label: "Kontakt" },
      ]},
      { label: "Matematiska vetenskaper", l2: [
        { label: "Forskning" },
        { label: "Utbildning" },
        { label: "Resurser och samverkan" },
        { label: "Medarbetare och kontakt" },
        { label: "Matematikbiblioteket" },
        { label: "Arbeta på Matematiska vetenskaper" },
      ]},
      { label: "Mechanical engineering", l2: [
        { label: "Forskning" },
        { label: "Utbildning" },
        { label: "Resurser och samarbeten" },
        { label: "Kontakt" },
      ]},
      { label: "Miljö- och energivetenskaper", l2: [
        { label: "Forskning" },
        { label: "Utbildning" },
        { label: "Chalmers Kraftcentral" },
        { label: "Kontakt" },
      ]},
      { label: "Mikroteknologi och nanovetenskap", l2: [
        { label: "Forskning" },
        { label: "Utbildning" },
        { label: "Resurser och samarbeten" },
        { label: "Kontakt" },
      ]},
      { label: "Teknikens ekonomi och organisation", l2: [
        { label: "Forskning" },
        { label: "Utbildning" },
        { label: "Centrum" },
        { label: "Kontakt" },
      ]},
      { label: "Vetenskapens kommunikation och lärande", l2: [
        { label: "Forskning" },
        { label: "Utbildning" },
        { label: "Samverkan" },
        { label: "Nyttiggörande" },
        { label: "Chalmers bibliotek" },
        { label: "Avdelningar" },
        { label: "Kontakt" },
        { label: "Institutionens podd - Insikten!" },
      ]},
      { label: "Chalmers Sjöfartshögskola", l2: [
        { label: "Utbildning" },
        { label: "Forskning" },
        { label: "Resurser och samarbeten" },
        { label: "Kontakt" },
      ]},
    ],
  },
];
